title: Coen Valk
subtitle: Software Engineer
description: Coen Valk's personal blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://coenvalk.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: coenvalk

include: ["_pages"]

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Build settings
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-include-cache

minimal_mistakes_skin: dark

paginate: 5
paginate_path: "/blog/page:num/"

teaser: /assets/images/blog.svg

logo: /assets/images/masthead.png

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      image: /assets/images/blog.svg
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

enable_copy_code_button: true

footer:
  links:
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/coen-valk/"
    - label: "GitHub"
      icon: "fa-brands fa-github"
      url: "https://github.com/coenvalk"
