title: Coen Valk
subtitle: Data Focused Engineer
email: valkc@rpi.edu
description: >- # this means to ignore newlines until "baseurl:"
  Coen Valk | Data Focused Engineer | Troy, NY
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: clcjvalk
github_username:  clcjvalk
linkedin_username: coen-valk-5b396911a

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jemoji

exclude:
  - scripts
  - notebooks

show_excerpts: true

