title: Coen Valk
email: valkc@rpi.edu
description: >- # this means to ignore newlines until "baseurl:"
  Data Focused Engineer
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://coenvalk.github.io" # the base hostname & protocol for your site, e.g. http://example.com

paginate: 5
markdown: kramdown
highlighter: rouge

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
