title: Coen Valk
description: RPI Computer Science 2020
show_downloads: false
theme: jekyll-theme-slate
footer-links:
  email: valkc@rpi.edu
  facebook: clcjvalk
  github: coenvalk
  instagram: coenvalk
  linkedin: coen-valk-5b396911a
